# Generated by Django 3.2 on 2021-04-21 04:42

import DA.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DA', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='day',
            field=DA.models.IntegerRangeField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info',
            name='end',
            field=models.TimeField(blank=True, default=DA.models.default_start_time),
        ),
        migrations.AddField(
            model_name='info',
            name='month',
            field=DA.models.IntegerRangeField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info',
            name='start',
            field=models.TimeField(blank=True, default=DA.models.default_start_time),
        ),
    ]
