# Generated by Django 3.2 on 2021-04-22 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DA', '0003_auto_20210422_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='entry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='DA.entry'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='info',
            name='text',
            field=models.TextField(),
        ),
    ]
