# Generated by Django 3.2 on 2021-04-23 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DA', '0004_auto_20210422_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='year',
            field=models.IntegerField(default=2021),
            preserve_default=False,
        ),
    ]
